apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dse
  name: dse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dse
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dse
    spec:
      containers:
      - args:
        - -s -g
        env:
        - name: DS_LICENSE
          value: accept
        image: datastax/dse-server:6.8.0
        imagePullPolicy: ""
        name: dse
        ports:
        - containerPort: 9042
        - containerPort: 8983
        - containerPort: 8182
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
